# Generated by Django 4.2.16 on 2024-10-08 07:45

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField(verbose_name=builtins.max)),
                ('page_count', models.IntegerField(verbose_name=builtins.max)),
                ('price', models.IntegerField(verbose_name=builtins.max)),
                ('author', models.CharField(max_length=60)),
                ('make_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guess_game.author')),
            ],
        ),
    ]
